[package]
name = "req"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
http = "1.0.0"
reqwest = "0.11.23"
tokio = { version = "*", features = ["full"] }
